### ISSUE TITLE
how to get vpn configuration from url by json ?

### ISSUE THREAD

**Issue by WorldProger** [neel-desh/ThundarrVPN#3]
how to get vpn configuration from url by json ?

**Comment by neel-desh** [comment]
You need to host the json file somewhere, let say you put json files on github, you need to get url for raw file like this `https://raw.githubusercontent.com/neel-desh/ThundarrVPN/main/app/src/main/assets/india.ovpn` the url will start from `raw.github...` and then read this file using over the internet  [read more](https://stackoverflow.com/questions/33229869/get-json-data-from-url-using-android) . and once you have the file present you can pass it to the function or constructor
